models/Pages.php
<?php

namespace app\models;

use Yii;
use app\components\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\Url;
use app\models\Lang;

class Pages extends \yii\db\ActiveRecord
{
    
    public static function tableName()
    {
        return '{{%pages}}';
    }

    public function scenarios()
    {
        return [
            'update' => ['name', 'content', 'sort'],
        ];
    }
    
    public function rules()
    {
        return [
        ];
    }
    
    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
        {
            $this->date_create = date("Y-m-d H:i:s");
        }

        return parent::beforeSave($insert);
    }

    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'Номер'),
            'sort' => Yii::t('app', 'Номер'),
        ];
    }

    public function getTranslation()
    {
        return $this->hasMany(PagesContent::className(), ['join_id' => 'id']);
    }

    public function getCurentLangPages()
    {
        
        $lang = Lang::getCurrent();
        return $this->hasMany(PagesContent::className(), ['join_id' => 'id'])->andWhere(['lang' => $lang->url]);
    }

}

models/Product.php
<?php

namespace app\models;

use Yii;
use app\components\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\Url;
use app\models\Lang;
use app\models\Currency;
use app\models\ProductContent;
use app\models\ProductAttr;

//address_status:  1-Show address, 0-Not show address,
//status:  1-Show, 0-Not show,
        
class Product extends \yii\db\ActiveRecord
{
    public $image_array;
    public static function tableName()
    {
        return '{{%product}}';
    }

    public function scenarios()
    {
        return [
            'new_product' => [
                    'product_type_id', 'category_id', 'object_id',
                    'country_id', 'region_id', 'city_id',
                    'object_area', 'address',
                    'address_status', 'year_of_construction', 
                    'user_id', 'price','price_usd', 'img_src',
                    'currency', 'status', 'image_array',
                ],
            'update_image' => ['img_src']
        ];
    }
    
    public function rules()
    {
        return [
            
        ];
    }

    public static function find()
    {
        $controllerName = Yii::$app->controller->id;
        $controllerAction = Yii::$app->controller->action->id;
        
        if ($controllerName == 'product' && $controllerAction == 'product') 
        {
            return parent::find();
        }
        elseif($controllerName == 'product')
        {
            return parent::find()->where(['>', 'status', 0]);
        }
        
        else
        {
            return parent::find()->andWhere(['status'=> 10]);
        }
    }
        
    public function beforeSave($insert)
    {
        if ($this->isNewRecord)
        {
            $this->date_create = date("Y-m-d H:i:s");
        }
        $this->price_usd = $this->saveInUsd($this->price, $this->currency);
        return parent::beforeSave($insert);
    }

    public function getCategory()
    {
        if(isset($this->product_type_id)){
            return $this->hasOne(Category::className(), ['id' => 'product_type_id']);
        }else{
            return new Category();
        } 
    }
    public function getTranslationCategory()
    {
        return $this->hasMany(CategoryContent::className(), ['join_id' => 'product_type_id']);
    }
    public function getRegion()
    {
        if(isset($this->region_id)){
            return $this->hasOne(States::className(), ['id' => 'region_id']);
        }else{
            return new States();
        }
    }
    public function getProdAttr()
    {
        return $this->hasOne(ProductAttr::className(), ['join_id' => 'id']);
    }
    public function getImages()
    {
        return $this->hasMany(ProductImage::className(), ['product_id' => 'id']);
    }

    public function getTranslation()
    {
        return $this->hasMany(ProductContent::className(), ['join_id' => 'id']);
    }

    public function getCurentLangProducts()
    {
        
        $leng = Lang::getCurrent();
        return $this->hasMany(ProductContent::className(), ['join_id' => 'id'])->andWhere(['lang' => $leng->url]);
    }
    public function getName()
    {
        $lang = Lang::getCurrent();
        $ProductContent = ProductContent::findOne([
            'join_id' => $this->id,
            'lang' => $lang->url,
        ]);
        return $ProductContent->name;
    }
    public function getCurrenc()
    {
        return $this->hasOne(Currency::className(), ['slug' => 'currency']);
    }

    public function getAbout()
    {
        $leng = Lang::getCurrent();
        $ProductContent = ProductContent::findOne([
            'join_id' => $this->id,
            'lang' => $leng->url,
        ]);
        return $ProductContent->content;
    }
    
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'Номер'),
            'product_type_id' => Yii::t('main', 'type_of_a_sentence'),
            'category_id' => Yii::t('main', 'Offer_Category'),
            'object_id' => Yii::t('main', 'Object_type'),
            'country_id' => Yii::t('main', 'country'),
            'region_id' => Yii::t('main', 'Region'),
            'city_id' => Yii::t('main', 'City'),
            'img_src' => Yii::t('main', 'Main_photo'),
            'object_area' => 'Жилая площадь',
            'address' => 'Адрес объекта на карте',
            'address_status' => Yii::t('main', 'Show_Address'),
            'year_of_construction' => Yii::t('main', 'Year_of_construction'),
            'price' => Yii::t('main', 'Enter_price'),
            'currency' => Yii::t('main', 'Enter_currency'),
            'status' => Yii::t('app', 'Status'),
        ];
    }
    public function saveInUsd($price, $currency)
    {
        if($currency!==1){
            $modelCurren = Currency::find()->where(['slug'=>$currency])->one();
            return $price*$modelCurren->value;
        }
        else{
            return $price;
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;


use app\models\Setting;
use Yii;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\helpers\Url;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\Product;
use app\models\Category;
use app\models\Pages;
use app\models\Partners;
use app\models\Reviews;
use app\models\Lang;
use app\models\States;
use app\models\UserInfo;
use yii\data\ActiveDataProvider;
use app\modules\administration\models\Pricing;



class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post','get'],
                ],
            ],
            'eauth' => [
                // required to disable csrf validation on OpenID requests
                'class' => \nodge\eauth\openid\ControllerBehavior::className(),
                'only' => ['login'],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionInvesticii()
    {
        $page = Pages::find()->where( ['slug'=>'investicii'] )->one();
        $this->view->params['menu_item']['investicii'] = 'headMenu';
        return $this->render('investicii', [
            'page'=> $page,
            'title'=> $page->curentLangPages[0]->name,
        ]);
    }
    public function actionUslugi()
    {
        $page = Pages::find()->where( ['slug'=>'uslugi'] )->one();
        $this->view->params['menu_item']['uslugi'] = 'headMenu';
        return $this->render('uslugi', [
            'page'=> $page,
            'title'=> $page->curentLangPages[0]->name,
        ]);
    }

    public function actionForOwners()
    {
        $page = Pages::find()->where( ['slug'=>'owners'] )->one();
        $this->view->params['menu_item']['owners'] = 'headMenu';
        return $this->render('owners', [
            'page'=> $page,
            'title'=> $page->curentLangPages[0]->name,
        ]);
    }

    public function actionAbout()
    {
        $howBuy = Pages::find()->where( ['slug'=>'how_buy'] )->one();
        $pos=strpos($howBuy->curentLangPages[0]->content, ' ', 1600);
        $strHowBuy = substr($howBuy->curentLangPages[0]->content,0,$pos);

        $aboutProg = Pages::find()->where( ['slug'=>'about_prog'] )->one();
        $ourPhilosof = Pages::find()->where( ['slug'=>'our_philosof'] )->one();
        $partners = Partners::find()->limit(5)->all();
        $this->view->params['menu_item']['about'] = 'headMenu';
        return $this->render('about',[
            'howBuy'=> $howBuy,
            'howBuyContent' => $strHowBuy,
            'aboutProg'=> $aboutProg,
            'ourPhilosof'=> $ourPhilosof,
            'partners'=> $partners,
            'title'=> $aboutProg->curentLangPages[0]->name,
        ]);
    }
    public function actionHowBuy()
    {
        $howBuy = Pages::find()->where( ['slug'=>'how_buy'] )->one();
        return $this->render('investicii', [
            'page'=> $howBuy,
            'title'=> $howBuy->curentLangPages[0]->name,
        ]);
    }
    public function actionPartners()
    {
        $partners = Partners::find()->all();
        $aboutPartner = Pages::find()->where( ['slug'=>'about_partner'] )->one();
        return $this->render('partners', [
            'partners'=> $partners,
            'aboutPartner'=> $aboutPartner,
            'title'=> Yii::t('main','Our_partners'),
        ]);
    }

    public function actionReviews()
    {
        $langLink = Lang::getCurrent()->url != Lang::getDefaultLang()->url ? '/'.Lang::getCurrent()->url : '';
        $newReview = new Reviews();
        
        if(Yii::$app->request->post()&&!Yii::$app->user->isGuest)
        {
            $newReview->load(\Yii::$app->request->post());
            if($newReview->save()){
                Yii::$app->session->setFlash('added');
                return $this->redirect($langLink.'/site/reviews');          
            }
  
        }
        if(!Yii::$app->user->isGuest and Yii::$app->user->identity->type=='admin'){
            if(isset($_GET['delete']))
            {
                $review = Reviews::find()->where(['id'=>$_GET['delete']])->one();
                $review->delete();
                Yii::$app->session->setFlash('deleted');
                return $this->redirect($langLink.'/site/reviews');
            }
            elseif(isset($_GET['confirm']))
            {
                $review = Reviews::find()->where(['id'=>$_GET['confirm']])->one();
                $review->status = 1;
                $review->save();
                Yii::$app->session->setFlash('confirm');
                return $this->redirect($langLink.'/site/reviews');
            }
            $reviewsFind = Reviews::find()->orderBy('status');
            $modelReviews = new ActiveDataProvider(['query' => $reviewsFind, 'pagination' => ['pageSize' => 18]]);
            $reviews = $modelReviews->getModels();
            $isAdmin = true;
            $isLogined = true;
        }else{
            $reviewsFind = Reviews::find()->where(['status'=>1])->orderBy(['date_create' => SORT_DESC]);
            $modelReviews = new ActiveDataProvider(['query' => $reviewsFind, 'pagination' => ['pageSize' => 18]]);
            $reviews = $modelReviews->getModels();
            $isAdmin = false;
            if(!Yii::$app->user->isGuest){
                $isLogined = true;
            }else{
                $isLogined = false;
            }            
        }

        return $this->render('reviews', [
            'pagination' => $modelReviews->pagination,
            'reviews'=> $reviews,
            'isAdmin'=> $isAdmin,
            'isLogined'=> $isLogined,
            'newReview'=> $newReview,
            'title'=> Yii::t('main','Reviews'),
        ]);
    }

    public function actionIndex()
    {
        $user_ids = $this->activeUserIds();

        $newProducts = Product::find()
        ->limit(8)
        ->andWhere(['user_id'=>$user_ids])
        ->orderBy([
            'date_create' => SORT_DESC
              ])
        ->all();
        
        $products = Product::find()->andWhere(['user_id'=>$user_ids])->all();
        $product_low = Product::find()
        ->limit(8)
        ->andWhere(['<=', 'price_usd', 150000])
        ->andWhere(['user_id'=>$user_ids])
        ->orderBy(['date_create' => SORT_DESC])->all();
        $product_vip = Product::find()
        ->limit(8)
        ->andWhere(['vip'=>1, 'user_id'=>$user_ids])
        ->orderBy(['date_create' => SORT_DESC])->all();

        $arrStates = States::find()->where(['country_id' => 107])->all();
        $categories = Category::find()->all();
        $this->view->params['menu_item']['index'] = 'headMenu';
        return $this->render('index', [
            'newProducts' => $newProducts,
            'products'=> $products,
            'categories'=> $categories,
            'product_low'=> $product_low,
            'product_vip'=> $product_vip,
            'arrStates'=> $arrStates,
            'title'=> Yii::t('main','home'),
        ]);
    }

    public function actionSearch()
    {
        if(Yii::$app->request->post())
        {
            $post_data = Yii::$app->request->post();

            $products = Product::find()
            ->joinWith('translation')
            ->andWhere(['like', 'name', $post_data['name']]);

            if($post_data['price']!==''){
                $prices = explode("-", $post_data['price']);
                $products->andWhere(['>=', 'price_usd', (int)$prices[0]]);
                $products->andWhere(['<=', 'price_usd', (int)$prices[1]]);
            }

            if($post_data['area']!==''){
                $areas = explode("-", $post_data['area']);
                $products->andWhere(['>=', 'object_area', (int)$areas[0]]);
                $products->andWhere(['<=', 'object_area', (int)$areas[1]]);
            }

            if($post_data['region']!==''){
                $products->andWhere(['region_id' => (int)$post_data['region']]);
            }
            if($post_data['category']!==''){

                $categories = Category::find()
                ->joinWith('translation')
                ->where([ 'like', 'category_content.name', $post_data['category'] ])
                ->all();
                $arrCategories = [];
                foreach ($categories as $category) {
                    $arrCategories[] = $category->id;
                }
                
                $products->andWhere([ 'category_id'=>$arrCategories ]);
            }
            
            $modelProducts = new ActiveDataProvider(['query' => $products, 'pagination' => ['pageSize' => 30]]);

            return $this->render('search', [
                'modelProducts' => $modelProducts->getModels(),
                'pagination' => $modelProducts->pagination
            ]);
        }
        else
        {
            $modelProducts = [];
            $pagination = [];

            return $this->render('search', [
                'modelProducts' => $modelProducts,
                'pagination' => $pagination
            ]);

views/site/contact.php
<?php
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use app\models\Lang;
$arraySetting = ArrayHelper::map(app\models\Setting::find()->all(),'key','value');
$langLink = Lang::getCurrent()->url != Lang::getDefaultLang()->url ? '/'.Lang::getCurrent()->url : '';
$this->title = $title;
?>

<div class="content">
    <div class="kontakti-head">
        <div class="container">
            <div class="col-xs-12 padd-zero style-padding-ul">
                <ul class="breadcrumb my-breadcrumb-style">
                    <li>
                        <a href="../" class="style-a-color"><?= Yii::t('main','home') ?></a>
                    </li>
                    <li>
                        <a class="style-a-color active-color"><?= Yii::t('main','contacts') ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="kontaki-content">
        <div class="container">
            <div class="col-xs-12">
                <p class="text-title-same"><?= Yii::t('main','contacts') ?></p>
            </div>
            <div class="col-xs-12 kontakt-location">
                <div class="col-xs-12 map-kontakt">
                   <!-- <img class='map-loc-kontakt' src='/img/map-kontakti.png'/>-->
                    <div id="map_container">
                        <div id="map" style="height:551px; width:100%;"></div>
                        <input type="hidden" value="<?=$arraySetting['adress']?>" required="required" name="search_address" class="form-control kart_city" id="searchTextField">
                    </div>
                    <div class="col-md-4 col-sm-5 block-inform-kontakt padd-zero">
                        <div class="col-xs-12 ">
                            <div class="col-xs-12 padd-numb-kontakti">
                                <p class="number-kontakt-block"><?=$arraySetting['phone']?></p>
                            </div>
                            <div class='col-xs-12 same-display otstup-left'>
                                <img style='float: left;' src="/img/navig-kontakti.png">
                                <div class="text-block-loc">
                                    <span class='loc-kontakt-style'><?=$arraySetting['adress']?></span>
                                </div>
                            </div>
                            <div class='col-xs-12 same-display'>
                                <img style='float: left;' src='/img/email-kontakti.png'/>
                                <div class="text-block-loc">
                                    <span class='loc-kontakt-style'><?=$arraySetting['email']?></span>
                                </div>
                            </div>
                            <div class='col-xs-12'>
                                <div class="col-xs-12 worck-graphik">
                                    <span class='worck-text'>
                                       <?= Yii::t('main','schedule_of_work') ?>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="div-border"></div>
                        <div class="col-xs-12 text-vertical-center online-padd">
                            <div class="col-xs-12 padd-zero">
                                <div class="col-lg-4 col-md-5">
                                    <span class="online-text"><?= Yii::t('main','We_are_online') ?>:</span>
                                </div>
                                <div class="col-md-6 online-img-style">
                                    <a href="<?=$arraySetting['fb_link']?>"><img src="/img/facebook_footer.png"></a>
                                    <a href="<?=$arraySetting['inst_link']?>"><img src="/img/instagram_footer.png"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 block-iform-mob padd-zero">
                    <div class="col-xs-12 padd-numb-kontakti">
                        <p class="number-kontakt-block"><?=$arraySetting['phone']?></p>
                    </div>
                    <div class='col-xs-12 same-display otstup-left'>
                        <img style='float: left;' src="/img/navig-kontakti.png">
                        <div class="text-block-loc">
                            <span class='loc-kontakt-style'><?=$arraySetting['adress']?></span>
                        </div>
                    </div>
                    <div class='col-xs-12 same-display'>
                        <img style='float: left;' src='/img/email-kontakti.png'/>
                        <div class="text-block-loc">
                            <span class='loc-kontakt-style'><?=$arraySetting['email']?></span>
                        </div>
                    </div>
                    <div class='col-xs-12'>
                        <div class="col-xs-12 worck-graphik">
                            <span class='worck-text'>
                                <?= Yii::t('main','schedule_of_work') ?>
                            </span>
                        </div>
                    </div>
                    <div class="div-border">

                    </div>
                    <div class="col-xs-12 text-vertical-center online-padd">
                        <div class="col-lg-4 col-md-5 col-sm-2 col-xs-4">
                            <span class="online-text"><?= Yii::t('main','We_are_online') ?>:</span>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6 online-img-style">
                            <a href="<?=$arraySetting['fb_link']?>"><img src="/img/facebook_footer.png"></a>
                            <a href="<?=$arraySetting['inst_link']?>"><img src="/img/instagram_footer.png"></a>
                        </div>
                    </div>
                </div>
                <form class="col-xs-12 question-contakt" id="ask_guestion_site">
                    <p class="question-title"><?= Yii::t('main','Have_questions') ?>?</p>
                    <div class="col-xs-12 padd-zero">
                        <div class="col-md-4 col-xs-12 padd-zero">
                            <input type="hidden" name="email_user" value="<?=$arraySetting['email']?>" >
                            <input type="text" name="name" placeholder="<?= Yii::t('main','Your_name') ?>:" class="form-style-kartochka"/>
                            <input type="text" name="email" placeholder="<?= Yii::t('main','Your_email_mail') ?>:" class="form-style-kartochka"/>
                        </div>
                        <div class="col-md-8 col-xs-12 otstup-message">
                            <textarea name="text" placeholder="<?= Yii::t('main','Your_message') ?>:" class="form-style-kartochka write-form-kontakti"></textarea>
                        </div>
                    </div>
                    <div class='col-xs-12 after-send-padd text-vertical-center text-center-mob'>
                        <div class="col-lg-2 col-sm-3">
                            <a class='send-button-contact'><?= Yii::t('main','Pay_now') ?></a>
                        </div>
                        <div class="col-lg-10 col-sm-9 mob-padd">
                            <span class='fancks-after-send'><?= Yii::t('main','Thank_you_for_contacting') ?></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-xs-12 buy-house-padd">
                <p class='text-title-same'><?= Html::encode($howBuy->curentLangPages[0]->name) ?></p>
                <span class='how-to-buy'>
                    <?= Html::decode($howBuyContent) ?>
                </span>
                <p class='read-next-press'><a href="<?=$langLink?>/site/how-buy">Читать дальше</a></p>
            </div>
        </div>
    </div>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php
    if (Yii::$app->getSession()->hasFlash('error')) {
        echo '<div class="alert alert-danger">'.Yii::$app->getSession()->getFlash('error').'</div>';
    }
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => [
            'class' => 'loginAndSingupForms'
         ],
        'layout' => 'horizontal',
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'placeholder'=>'Ваш логин'])->label(false) ?>

        <?= $form->field($model, 'password')->passwordInput(['placeholder'=>'Ваш пароль'])->label(false) ?>

        <?= $form->field($model, 'rememberMe')->checkbox() ?>
        

        <div class="form-group">
            <div class="col-lg-12">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>
        <?= HTML::a(Yii::t('main', 'Forgot password?'),Url::home().'site/request-password-reset');  ?>
    <?php ActiveForm::end(); ?>

</div>

views/site/search.php
<?php
use yii\helpers\Html;
use yii\widgets\LinkPager;
use app\models\Lang;
$langLink = Lang::getCurrent()->url != Lang::getDefaultLang()->url ? '/'.Lang::getCurrent()->url : '';
?>
<div class="content">
    <div class="arenda-head">
        <div class="container">
            <div class="col-xs-12 padd-zero style-padding-ul">
                <ul class="breadcrumb my-breadcrumb-style">
                    <li>
                        <a class="style-a-color" href="../"><?= Yii::t('main','home') ?></a>
                    </li>
                    <li>
                        <a class="style-a-color active-color">Поиск</a>
                    </li>
                </ul>
                <p class="text-title-same">Результаты Поиска</p>
            </div>
        </div>
    </div>
    <div class="arenda-content search-result-content">
        <div class="container">
            <div class="col-xs-12 padd-zero" style="padding-bottom: 10px !important;">

                    <?php if(count($modelProducts)) : ?>
                        <?php foreach ($modelProducts as $product): ?>
                        <a href="<?=$langLink?>/product/<?= Html::encode($product->id) ?>">
                        <div class="content-class-style"><!-- start product container -->
                            <div class="col-xs-12 hover-div-slider padd-zero"
                            style="background-image: url(/images/product/<?= Html::encode($product->img_src) ?>);">
                                <div class="col-xs-12 padd-zero hov_img_none">
                                </div>
                                <div class="change-hover">
                                    <div class="col-xs-12 padd-zero style_border">
                                        <div class="col-xs-12">
                                            <p class="title_room">
                                                <?= Html::encode($product->name) ?>
                                            </p>
                                            <div class="width_style">
                                                <span class="span-title">Категория:</span> 
                                                <span class="span-text">
                                                    <?= Html::encode($product->category->name) ?>
                                                </span>
                                            </div>
                                            <div class="width_style">
                                                <span class="span-title">Площадь:</span> 
                                                <span class="span-text">
                                                    <?= Html::encode($product->object_area) ?>
                                                </span>
                                            </div>
                                            <div class="width_style">
                                                <span class="span-title">Регион:</span> 
                                                <span class="span-text">
                                                    <?= Html::encode($product->region->name) ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 padd-zero style-padd-div-same">
                                        <div class="col-sm-7 col-xs-7">
                                            <p class="money_style">
                                            <?= Html::encode($product->currenc->name.' '.$product->price) ?>
                                            </p>
                                        </div>
                                        <div class="col-sm-2 col-xs-2 padd-zero">
                                            <img class="style-img shower_class" src="/img/shower_icon.png">
                                            <span class="numb-style-text">2</span>
                                        </div>
                                        <div class="col-sm-3 col-xs-3 padd-zero ">
                                            <img class="style-img bed_class" src="/img/bed_icon.png">
                                            <span class="numb-style-text">3</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div><!-- end product container -->
                        </a>
                        <?php endforeach; ?>
                        <?= LinkPager::widget(['pagination'=>$pagination]);  ?>
                    <?php else: ?>
                    <h2 id="notResults">Ничего не найдено</h2>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>